# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='desc',
            new_name='courseDesc',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='name',
            new_name='courseName',
        ),
    ]
